### ISSUE TITLE
BurritoDoggie

### ISSUE THREAD

**Issue by TheCollinsByte** [BurritoDoggie/frontend-mentor-card-component#1]
I am out from fm i hope your hppy nw.

**Comment by BurritoDoggie** [comment]
wait what?

**Comment by TheCollinsByte** [comment]
You will never understand

**Comment by BurritoDoggie** [comment]
uhm...

dont mean to be rude... who r u?

**Comment by TheCollinsByte** [comment]
The gut you hate

**Comment by BurritoDoggie** [comment]
u are the gut i hate?

**Comment by TheCollinsByte** [comment]
First Two words in the repository name

**Comment by TheCollinsByte** [comment]
You a the person who made me to be out. and i am now out from the community

**Comment by TheCollinsByte** [comment]
I hope that sounds great. LOL

**Comment by BurritoDoggie** [comment]
uhm

**Comment by BurritoDoggie** [comment]
just leave me alone pls

**Comment by TheCollinsByte** [comment]
Okay
